clear;clc;close all;
load V;
addpath(genpath('./script'));
addpath(genpath('/media/zzr/Data/git/code/trunk/matlab/general'));
addpath(genpath('/media/zzr/Data/git/code/trunk/matlab/images'));
templatevolume = V_img{2};
inputvolume = V_img{2};
options.docheck = false;
options.rescaleMax = 2000;
[outputvolume, ~] = int_stdn_landmarks(inputvolume,templatevolume, options);